# Generated by Django 5.1.7 on 2025-04-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bidder",
        ),
    ]
